AutoItSetOption("SendKeyDelay", 500)
;~ Sleep(7000)
WinActivate("[CLASS:TTOTAL_CMD]")
;Send("^{NUMPADADD}")
send("^A")
;~ ConsoleWrite(@MDAY&@CRLF)
Send("!+{F5}")
Send("{ENTER}")
;~ Send("{TAB}{DOWN 3}{SPACE}{ENTER}")
;~ Send("{ALT}")
;~ Sleep(500)
;~ Send("{RIGHT 2}")
;~ Send("{DOWN 3}")
;~ Send("{ENTER}")
;~ ConsoleWrite("END    ")
